export type CountryEntry = { code: string; name: string };

export const COUNTRY_LIST: CountryEntry[] = [
  { code: "PH", name: "Philippines" },
  { code: "AU", name: "Australia" },
  { code: "CA", name: "Canada" },
  { code: "CN", name: "China" },
  { code: "DE", name: "Germany" },
  { code: "ES", name: "Spain" },
  { code: "FR", name: "France" },
  { code: "GB", name: "United Kingdom" },
  { code: "HK", name: "Hong Kong" },
  { code: "ID", name: "Indonesia" },
  { code: "IN", name: "India" },
  { code: "JP", name: "Japan" },
  { code: "KR", name: "South Korea" },
  { code: "MY", name: "Malaysia" },
  { code: "NZ", name: "New Zealand" },
  { code: "SG", name: "Singapore" },
  { code: "TH", name: "Thailand" },
  { code: "TW", name: "Taiwan" },
  { code: "US", name: "United States" },
  { code: "VN", name: "Vietnam" },
];

export const PHONE_CODES: { code: string; label: string }[] = [
  { code: "+63", label: "+63 PH" },
  { code: "+1",  label: "+1  US/CA" },
  { code: "+7",  label: "+7  RU" },
  { code: "+44", label: "+44 GB" },
  { code: "+49", label: "+49 DE" },
  { code: "+60", label: "+60 MY" },
  { code: "+61", label: "+61 AU" },
  { code: "+65", label: "+65 SG" },
  { code: "+66", label: "+66 TH" },
  { code: "+81", label: "+81 JP" },
  { code: "+82", label: "+82 KR" },
  { code: "+84", label: "+84 VN" },
  { code: "+86", label: "+86 CN" },
  { code: "+852", label: "+852 HK" },
  { code: "+886", label: "+886 TW" },
  { code: "+91", label: "+91 IN" },
  { code: "+62", label: "+62 ID" },
  { code: "+64", label: "+64 NZ" },
];
