export type CountryEntry = { code: string; name: string };

export const COUNTRY_LIST: CountryEntry[] = [
  { code: "PH", name: "Philippines" },
  { code: "AR", name: "Argentina" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "BE", name: "Belgium" },
  { code: "BR", name: "Brazil" },
  { code: "CA", name: "Canada" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" },
  { code: "CZ", name: "Czech Republic" },
  { code: "DK", name: "Denmark" },
  { code: "EG", name: "Egypt" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "DE", name: "Germany" },
  { code: "GR", name: "Greece" },
  { code: "HK", name: "Hong Kong" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JP", name: "Japan" },
  { code: "MY", name: "Malaysia" },
  { code: "MX", name: "Mexico" },
  { code: "NL", name: "Netherlands" },
  { code: "NZ", name: "New Zealand" },
  { code: "NG", name: "Nigeria" },
  { code: "NO", name: "Norway" },
  { code: "PK", name: "Pakistan" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russia" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SG", name: "Singapore" },
  { code: "ZA", name: "South Africa" },
  { code: "KR", name: "South Korea" },
  { code: "ES", name: "Spain" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "TW", name: "Taiwan" },
  { code: "TH", name: "Thailand" },
  { code: "TR", name: "Turkey" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "VN", name: "Vietnam" },
];

export const PHONE_CODES: { code: string; label: string }[] = [
  { code: "+63", label: "+63 PH" },
  { code: "+1",  label: "+1  US/CA" },
  { code: "+7",  label: "+7  RU" },
  { code: "+44", label: "+44 GB" },
  { code: "+49", label: "+49 DE" },
  { code: "+60", label: "+60 MY" },
  { code: "+61", label: "+61 AU" },
  { code: "+65", label: "+65 SG" },
  { code: "+66", label: "+66 TH" },
  { code: "+81", label: "+81 JP" },
  { code: "+82", label: "+82 KR" },
  { code: "+84", label: "+84 VN" },
  { code: "+86", label: "+86 CN" },
  { code: "+852", label: "+852 HK" },
  { code: "+886", label: "+886 TW" },
  { code: "+91", label: "+91 IN" },
  { code: "+62", label: "+62 ID" },
  { code: "+64", label: "+64 NZ" },
];
